title: Chew Chiu Xian
logo: file:///C:/Users/chiux/OneDrive/Documents/img/image.webp 
description: Data Engineering Student in Universiti Teknologi Malaysia
show_download: false
theme: jekyll-theme-minimal
